CREATE TABLE des_azurian.record(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
FIRSTNAME VARCHAR(100) NOT NULL,
LASTNAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
ADDRESS VARCHAR(500) NOT NULL,
PHONENUMBER VARCHAR(100) NOT NULL
);